// Infrastructure Security — deterministic mock data
import type {
  WAFWebACL, CloudFrontDistribution, APIGatewayEndpoint,
  SecurityGroupFinding, NACLIssue, VPCFlowLogEntry,
  ComputeInstanceFinding, LambdaFinding,
  ConnectivityTest, RouteEntry, DNSResolution,
  InfraFinding, Scenario,
} from "./types";

function ago(h: number) { return new Date(Date.now() - h * 3_600_000).toISOString(); }
function fromNow(h: number) { return new Date(Date.now() + h * 3_600_000).toISOString(); }

// ─── Shared findings used across edge surfaces ────────────────────────────────

const EDGE_FINDINGS: InfraFinding[] = [
  {
    id: "ef-001",
    title: "CloudFront distribution not protected by WAF Web ACL",
    severity: "CRITICAL",
    confidence: "HIGH",
    description: "Distribution E1A2B3C4D5E6F7 serves production traffic on cloudsec.acme.io without an associated WAF Web ACL. Any SQL injection, XSS, or L7 DDoS attempts will reach the origin unfiltered.",
    resource_id: "E1A2B3C4D5E6F7",
    resource_type: "CloudFront Distribution",
    region: "us-east-1",
    lifecycle: "triaged",
    created_at: ago(14),
    sla_deadline: fromNow(-2),
    sla_breached: true,
    assignee: "alice.chen",
    mitre_technique: "T1190",
    remediation_steps: [
      "Create or select a WAF v2 Web ACL with AWS Managed Rules enabled",
      "Associate the Web ACL to distribution E1A2B3C4D5E6F7 via WAF console or API",
      "Enable logging to S3/Firehose for audit trail",
      "Test with OWASP test vectors before promoting to prod",
    ],
    evidence: [
      { id: "ev-001", type: "api_response", label: "GetDistributionConfig response", content: `{"WebACLId":"","Origins":[{"DomainName":"api-prod.internal"}]}`, collected_at: ago(14) },
      { id: "ev-002", type: "log_snippet", label: "WAF association audit log (empty)", content: `No WAF association events found for E1A2B3C4D5E6F7 in last 90 days`, collected_at: ago(13) },
    ],
    timeline: [
      { id: "t-001", timestamp: ago(14), actor: "System", actor_type: "system", action: "Finding detected via Config rule cloudfront-waf-enabled" },
      { id: "t-002", timestamp: ago(13), actor: "alice.chen", actor_type: "engineer", action: "Triaged", note: "Confirmed with infra team — WAF was removed during CDN migration, not re-attached" },
    ],
    integration_deps: ["GET /2019-03-26/distribution/{id}/config", "PUT /wafv2/webacl/{id}/disassociate-webacl", "POST /wafv2/webacl/{id}/associate-webacl"],
  },
  {
    id: "ef-002",
    title: "API Gateway stage 'prod' has no authentication",
    severity: "HIGH",
    confidence: "HIGH",
    description: "REST API acme-data-api (agr-0a1b2c) stage 'prod' uses auth_type NONE with no resource policy. All endpoints are publicly accessible without credentials.",
    resource_id: "agr-0a1b2c/prod",
    resource_type: "API Gateway Stage",
    region: "us-east-1",
    lifecycle: "open",
    created_at: ago(3),
    sla_deadline: fromNow(21),
    sla_breached: false,
    remediation_steps: [
      "Attach a Lambda authorizer or enable AWS_IAM auth on the stage",
      "Add a resource policy restricting callers to known CIDR/principals",
      "Enable WAF Web ACL association on the API stage",
      "Enable access logging to CloudWatch for audit",
    ],
    evidence: [
      { id: "ev-003", type: "api_response", label: "GetStage response", content: `{"authorizationType":"NONE","methodSettings":{},"accessLogSettings":null}`, collected_at: ago(3) },
    ],
    timeline: [
      { id: "t-003", timestamp: ago(3), actor: "System", actor_type: "system", action: "Finding detected via Security Hub rule api-gw-execution-logging-enabled" },
    ],
    integration_deps: ["GET /restapis/{id}/stages/{stageName}", "PUT /restapis/{id}/stages/{stageName} (add authorizer)", "POST /2015-07-09/apis/{id}/stages/{stage}/policy"],
  },
  {
    id: "ef-003",
    title: "WAF Web ACL missing managed rule group for SQLi",
    severity: "HIGH",
    confidence: "MEDIUM",
    description: "WAF ACL waf-prod-alb-acl (acl-0dead) has only rate-based rules. No AWS-managed SQLi or XSS rule group is active. SQLi payloads will pass through.",
    resource_id: "acl-0dead",
    resource_type: "WAF Web ACL",
    region: "us-east-1",
    lifecycle: "open",
    created_at: ago(48),
    sla_deadline: fromNow(-24),
    sla_breached: true,
    remediation_steps: [
      "Add AWSManagedRulesSQLiRuleSet to the Web ACL",
      "Add AWSManagedRulesCommonRuleSet for XSS and common threats",
      "Set action to Block (not Count) in production",
      "Review false-positive rate in Count mode for 24h before switching to Block",
    ],
    evidence: [
      { id: "ev-004", type: "api_response", label: "ListWebACLs rules", content: `{"Rules":[{"Name":"RateLimit","Priority":0,"Action":{"Block":{}}}],"ManagedRuleGroups":[]}`, collected_at: ago(48) },
    ],
    timeline: [
      { id: "t-004", timestamp: ago(48), actor: "System", actor_type: "system", action: "Detected: WAF rule gap audit" },
      { id: "t-005", timestamp: ago(36), actor: "bob.martinez", actor_type: "engineer", action: "Acknowledged", note: "Escalated to WAF team — pending approval for managed rule costs (~$5/month)" },
    ],
    integration_deps: ["GET /wafv2/webacl/{id}", "PUT /wafv2/webacl/{id} (add managed rule groups)", "GET /wafv2/available-managed-rule-groups"],
  },
];

// ─── WAF Web ACLs ──────────────────────────────────────────────────────────────

export const MOCK_WAF_ACLS: WAFWebACL[] = [
  {
    id: "acl-0dead",
    name: "waf-prod-alb-acl",
    region: "us-east-1",
    associated_resource: "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/prod-alb/0ab1cd",
    resource_type: "ALB",
    rule_count: 1,
    blocked_24h: 2847,
    allowed_24h: 1_204_931,
    rate_limited_24h: 312,
    status: "degraded",
    findings: [EDGE_FINDINGS[2]],
  },
  {
    id: "acl-0beef",
    name: "waf-staging-cf-acl",
    region: "us-east-1",
    associated_resource: "arn:aws:cloudfront::123456789012:distribution/E9X8Y7Z6W5V4",
    resource_type: "CloudFront",
    rule_count: 8,
    blocked_24h: 127,
    allowed_24h: 88_234,
    rate_limited_24h: 45,
    status: "healthy",
    findings: [],
  },
  {
    id: "acl-unassoc",
    name: "waf-unused-acl",
    region: "us-east-1",
    associated_resource: "",
    resource_type: "UNASSOCIATED",
    rule_count: 4,
    blocked_24h: 0,
    allowed_24h: 0,
    rate_limited_24h: 0,
    status: "unknown",
    findings: [],
  },
];

// ─── CloudFront distributions ─────────────────────────────────────────────────

export const MOCK_CF_DISTRIBUTIONS: CloudFrontDistribution[] = [
  {
    id: "E1A2B3C4D5E6F7",
    domain_name: "cloudsec.acme.io",
    origin: "api-prod.internal.acme.com",
    waf_acl_id: null,
    https_enforced: true,
    geo_restriction: false,
    access_logging: false,
    price_class: "PriceClass_100",
    status: "critical",
    findings: [EDGE_FINDINGS[0]],
  },
  {
    id: "E9X8Y7Z6W5V4",
    domain_name: "staging.acme.io",
    origin: "s3-website-us-east-1.amazonaws.com/acme-staging",
    waf_acl_id: "acl-0beef",
    https_enforced: true,
    geo_restriction: true,
    access_logging: true,
    price_class: "PriceClass_100",
    status: "healthy",
    findings: [],
  },
  {
    id: "EABC123DEF456",
    domain_name: "assets.acme.io",
    origin: "acme-static-assets.s3.amazonaws.com",
    waf_acl_id: null,
    https_enforced: false,
    geo_restriction: false,
    access_logging: false,
    price_class: "PriceClass_All",
    status: "degraded",
    findings: [],
  },
];

// ─── API Gateway endpoints ─────────────────────────────────────────────────────

export const MOCK_API_GW: APIGatewayEndpoint[] = [
  {
    id: "agr-0a1b2c/prod",
    name: "acme-data-api",
    stage: "prod",
    type: "REST",
    auth_type: "NONE",
    waf_attached: false,
    throttle_burst: 5000,
    throttle_rate: 10000,
    endpoint_type: "REGIONAL",
    status: "critical",
    findings: [EDGE_FINDINGS[1]],
  },
  {
    id: "agr-0d4e5f/v1",
    name: "acme-internal-api",
    stage: "v1",
    type: "REST",
    auth_type: "AWS_IAM",
    waf_attached: true,
    throttle_burst: 2000,
    throttle_rate: 5000,
    endpoint_type: "PRIVATE",
    status: "healthy",
    findings: [],
  },
  {
    id: "agr-0g7h8i/prod",
    name: "acme-ws-api",
    stage: "prod",
    type: "WebSocket",
    auth_type: "LAMBDA_AUTHORIZER",
    waf_attached: false,
    throttle_burst: 500,
    throttle_rate: 1000,
    endpoint_type: "REGIONAL",
    status: "degraded",
    findings: [],
  },
];

// ─── Security Group findings ──────────────────────────────────────────────────

export const MOCK_SG_FINDINGS: SecurityGroupFinding[] = [
  {
    id: "sgf-001",
    sg_id: "sg-0abc1234",
    sg_name: "prod-web-sg",
    vpc_id: "vpc-0123abcd",
    direction: "INBOUND",
    protocol: "TCP",
    port_range: "3389",
    source_cidr: "0.0.0.0/0",
    severity: "CRITICAL",
    description: "RDP port open to the world. Any internet host can attempt authentication against prod-web servers.",
    attached_resources: 4,
    lifecycle: "triaged",
    created_at: ago(6),
    sla_deadline: fromNow(-2),
    sla_breached: true,
    remediation_steps: [
      "Restrict source CIDR to corporate VPN range (10.100.0.0/16)",
      "Consider removing RDP entirely if SSM Session Manager is available",
      "Enable VPC Flow Logs if not already enabled to capture access attempts",
    ],
  },
  {
    id: "sgf-002",
    sg_id: "sg-0def5678",
    sg_name: "prod-db-sg",
    vpc_id: "vpc-0123abcd",
    direction: "INBOUND",
    protocol: "TCP",
    port_range: "5432",
    source_cidr: "0.0.0.0/0",
    severity: "CRITICAL",
    description: "PostgreSQL port open to all IPs. Production database is directly accessible from the internet.",
    attached_resources: 2,
    lifecycle: "open",
    created_at: ago(1.5),
    sla_deadline: fromNow(2.5),
    sla_breached: false,
    remediation_steps: [
      "Immediately restrict to application tier SG (sg-0abc1234) as source",
      "Enable enhanced monitoring on RDS to catch any unauthorized queries",
      "Rotate database credentials as precautionary measure",
    ],
  },
  {
    id: "sgf-003",
    sg_id: "sg-0ghi9012",
    sg_name: "bastion-sg",
    vpc_id: "vpc-0123abcd",
    direction: "INBOUND",
    protocol: "TCP",
    port_range: "22",
    source_cidr: "0.0.0.0/0",
    severity: "HIGH",
    description: "SSH accessible from all internet IPs on bastion host. Consider restricting to known IPs or using SSM.",
    attached_resources: 1,
    lifecycle: "in_progress",
    created_at: ago(72),
    sla_deadline: fromNow(0),
    sla_breached: false,
    remediation_steps: [
      "Add specific CIDR blocks for known office/VPN egress IPs",
      "Enable EC2 Instance Connect as a more controlled alternative",
      "Review CloudTrail for recent SSH auth attempts",
    ],
  },
  {
    id: "sgf-004",
    sg_id: "sg-0jkl3456",
    sg_name: "monitoring-sg",
    vpc_id: "vpc-0456efgh",
    direction: "INBOUND",
    protocol: "TCP",
    port_range: "8080-8090",
    source_cidr: "10.0.0.0/8",
    severity: "MEDIUM",
    description: "Internal monitoring ports open to entire 10.0.0.0/8 RFC1918 space. Should be restricted to monitoring subnet.",
    attached_resources: 6,
    lifecycle: "open",
    created_at: ago(168),
    sla_deadline: fromNow(504),
    sla_breached: false,
    remediation_steps: [
      "Restrict source to monitoring subnet CIDR (10.50.0.0/24)",
      "Audit what services are listening on these ports",
    ],
  },
  {
    id: "sgf-005",
    sg_id: "sg-0abc1234",
    sg_name: "prod-web-sg",
    vpc_id: "vpc-0123abcd",
    direction: "OUTBOUND",
    protocol: "ALL",
    port_range: "ALL",
    source_cidr: "0.0.0.0/0",
    severity: "LOW",
    description: "Unrestricted outbound rule. While common, consider restricting to known destinations to limit lateral movement blast radius.",
    attached_resources: 4,
    lifecycle: "risk_accepted",
    created_at: ago(720),
    sla_deadline: fromNow(9999),
    sla_breached: false,
    remediation_steps: [
      "Enumerate required outbound destinations",
      "Create explicit outbound rules per destination",
      "Remove the catch-all outbound rule",
    ],
  },
];

// ─── NACL issues ──────────────────────────────────────────────────────────────

export const MOCK_NACL_ISSUES: NACLIssue[] = [
  {
    id: "nacl-001",
    nacl_id: "acl-0abc1234",
    vpc_id: "vpc-0123abcd",
    rule_number: 100,
    direction: "INBOUND",
    action: "ALLOW",
    protocol: "TCP",
    port_range: "0-65535",
    cidr: "0.0.0.0/0",
    severity: "HIGH",
    description: "NACL rule 100 allows all TCP inbound from internet, effectively bypassing per-SG restrictions for some traffic paths.",
  },
  {
    id: "nacl-002",
    nacl_id: "acl-0def5678",
    vpc_id: "vpc-0456efgh",
    rule_number: 200,
    direction: "OUTBOUND",
    action: "ALLOW",
    protocol: "ALL",
    port_range: "ALL",
    cidr: "0.0.0.0/0",
    severity: "MEDIUM",
    description: "Unrestricted outbound at NACL level provides no defense-in-depth for data exfiltration scenarios.",
  },
];

// ─── VPC Flow Log coverage ────────────────────────────────────────────────────

export const MOCK_VPC_FLOW_LOGS: VPCFlowLogEntry[] = [
  { vpc_id: "vpc-0123abcd", vpc_name: "prod-vpc", flow_logs_enabled: true, destination: "s3://acme-flow-logs/prod/", destination_type: "S3", retention_days: 90, coverage: "healthy" },
  { vpc_id: "vpc-0456efgh", vpc_name: "staging-vpc", flow_logs_enabled: true, destination: "/aws/vpc/staging-flow-logs", destination_type: "CloudWatch", retention_days: 14, coverage: "degraded" },
  { vpc_id: "vpc-0789ijkl", vpc_name: "dev-vpc", flow_logs_enabled: false, destination: null, destination_type: null, retention_days: null, coverage: "critical" },
  { vpc_id: "vpc-0mnopqrs", vpc_name: "shared-services-vpc", flow_logs_enabled: true, destination: "s3://acme-flow-logs/shared/", destination_type: "S3", retention_days: 365, coverage: "healthy" },
];

// ─── Compute instance findings ────────────────────────────────────────────────

export const MOCK_COMPUTE_FINDINGS: ComputeInstanceFinding[] = [
  {
    id: "cf-001",
    instance_id: "i-0a1b2c3d4e5f6789",
    instance_name: "prod-web-01",
    instance_type: "c5.2xlarge",
    region: "us-east-1",
    az: "us-east-1a",
    public_ip: "54.83.21.45",
    ssm_managed: true,
    imdsv2_required: false,
    ebs_encrypted: true,
    patch_status: "critical",
    severity: "CRITICAL",
    top_finding: "IMDSv2 not enforced — metadata service accessible via v1 (SSRF risk)",
    lifecycle: "in_progress",
    created_at: ago(8),
    sla_deadline: fromNow(-4),
    sla_breached: true,
    remediation_steps: [
      "Run: aws ec2 modify-instance-metadata-options --instance-id i-0a1b2c3d4e5f6789 --http-tokens required",
      "Verify application does not depend on IMDSv1 before enforcing",
      "Enable IMDSv2 in launch template to prevent regression",
    ],
  },
  {
    id: "cf-002",
    instance_id: "i-0b2c3d4e5f678901",
    instance_name: "prod-worker-02",
    instance_type: "m5.xlarge",
    region: "us-east-1",
    az: "us-east-1b",
    public_ip: null,
    ssm_managed: false,
    imdsv2_required: false,
    ebs_encrypted: false,
    patch_status: "behind_3_months",
    severity: "HIGH",
    top_finding: "Not SSM managed, EBS volumes unencrypted, patches 3+ months behind",
    lifecycle: "open",
    created_at: ago(96),
    sla_deadline: fromNow(-48),
    sla_breached: true,
    remediation_steps: [
      "Install SSM Agent and attach AmazonSSMManagedInstanceCore policy to instance role",
      "Encrypt EBS volumes by creating encrypted snapshots and replacing volumes",
      "Apply OS patches via SSM Patch Manager or instance replacement",
    ],
  },
  {
    id: "cf-003",
    instance_id: "i-0c3d4e5f67890123",
    instance_name: "dev-bastion",
    instance_type: "t3.micro",
    region: "us-east-1",
    az: "us-east-1c",
    public_ip: "18.206.140.77",
    ssm_managed: true,
    imdsv2_required: true,
    ebs_encrypted: true,
    patch_status: "behind_1_month",
    severity: "MEDIUM",
    top_finding: "Public IP with SSH open (see sg-0ghi9012) — patches slightly behind",
    lifecycle: "triaged",
    created_at: ago(24),
    sla_deadline: fromNow(48),
    sla_breached: false,
    remediation_steps: [
      "Replace SSH access with SSM Session Manager (eliminate public IP need)",
      "Apply current OS patches",
      "Schedule regular automated patching via SSM Patch Manager",
    ],
  },
  {
    id: "cf-004",
    instance_id: "i-0d4e5f6789012345",
    instance_name: "prod-api-01",
    instance_type: "c5.4xlarge",
    region: "us-west-2",
    az: "us-west-2b",
    public_ip: null,
    ssm_managed: true,
    imdsv2_required: true,
    ebs_encrypted: true,
    patch_status: "current",
    severity: "LOW",
    top_finding: "Security group allows monitoring traffic from oversized CIDR",
    lifecycle: "risk_accepted",
    created_at: ago(504),
    sla_deadline: fromNow(9999),
    sla_breached: false,
    remediation_steps: ["Restrict monitoring SG source to monitoring subnet CIDR"],
  },
];

// ─── Lambda findings ──────────────────────────────────────────────────────────

export const MOCK_LAMBDA_FINDINGS: LambdaFinding[] = [
  {
    id: "lf-001",
    function_name: "acme-data-processor",
    runtime: "python3.9",
    region: "us-east-1",
    execution_role_arn: "arn:aws:iam::123456789012:role/LambdaFullAccess",
    public_url: false,
    vpc_attached: false,
    env_vars_encrypted: false,
    severity: "HIGH",
    finding: "Execution role has AdministratorAccess policy attached. Function can perform any AWS action.",
    lifecycle: "open",
    created_at: ago(12),
    remediation_steps: [
      "Create a least-privilege role with only required permissions",
      "Remove AdministratorAccess and replace with resource-scoped policies",
      "Enable function URL auth (AWS_IAM) if public URL is needed",
    ],
  },
  {
    id: "lf-002",
    function_name: "acme-auth-hook",
    runtime: "nodejs18.x",
    region: "us-east-1",
    execution_role_arn: "arn:aws:iam::123456789012:role/AuthLambdaRole",
    public_url: true,
    vpc_attached: false,
    env_vars_encrypted: true,
    severity: "MEDIUM",
    finding: "Function URL exposed publicly with no auth. Any internet caller can invoke the auth hook.",
    lifecycle: "triaged",
    created_at: ago(36),
    remediation_steps: [
      "Set function URL AuthType to AWS_IAM",
      "Or remove the public URL and invoke only via API Gateway with auth",
      "Review function logs for unauthorized invocation attempts",
    ],
  },
  {
    id: "lf-003",
    function_name: "acme-report-generator",
    runtime: "python3.11",
    region: "us-east-1",
    execution_role_arn: "arn:aws:iam::123456789012:role/ReportLambdaRole",
    public_url: false,
    vpc_attached: false,
    env_vars_encrypted: false,
    severity: "MEDIUM",
    finding: "Environment variables contain database credentials in plaintext (DB_PASSWORD detected).",
    lifecycle: "open",
    created_at: ago(2),
    remediation_steps: [
      "Move credentials to Secrets Manager and use secretsmanager:GetSecretValue in the role",
      "Remove plaintext DB_PASSWORD from function configuration",
      "Rotate the exposed database credentials immediately",
    ],
  },
];

// ─── Connectivity tests ───────────────────────────────────────────────────────

export const MOCK_CONNECTIVITY_TESTS: ConnectivityTest[] = [
  {
    id: "ct-001",
    source: "i-0a1b2c3d4e5f6789",
    source_type: "EC2",
    destination: "database.prod.internal",
    destination_type: "RDS",
    port: 5432,
    protocol: "TCP",
    result: "blocked",
    hops: [
      { index: 1, component: "sg-0abc1234 (prod-web-sg)", type: "SecurityGroup", action: "ALLOW", detail: "Outbound rule 0.0.0.0/0 ALL matches" },
      { index: 2, component: "rtb-0prodmain", type: "RouteTable", action: "ROUTE", detail: "10.0.0.0/16 → local" },
      { index: 3, component: "sg-0def5678 (prod-db-sg)", type: "SecurityGroup", action: "DENY", detail: "No inbound rule allows sg-0abc1234 on port 5432" },
    ],
    ran_at: ago(0.1),
    duration_ms: 234,
    blocking_component: "sg-0def5678",
    blocking_reason: "Security group prod-db-sg has no rule permitting inbound TCP 5432 from prod-web-sg",
  },
  {
    id: "ct-002",
    source: "i-0b2c3d4e5f678901",
    source_type: "EC2",
    destination: "169.254.169.254",
    destination_type: "Service",
    port: 80,
    protocol: "TCP",
    result: "reachable",
    hops: [
      { index: 1, component: "sg-worker-sg", type: "SecurityGroup", action: "ALLOW", detail: "Default outbound 0.0.0.0/0 matches" },
      { index: 2, component: "IMDSv2 endpoint", type: "ENI", action: "FORWARD", detail: "IMDS endpoint reachable — IMDSv1 also accepted (token not required)" },
    ],
    ran_at: ago(0.2),
    duration_ms: 12,
  },
  {
    id: "ct-003",
    source: "Lambda:acme-data-processor",
    source_type: "Lambda",
    destination: "s3.amazonaws.com",
    destination_type: "S3_Endpoint",
    port: 443,
    protocol: "TCP",
    result: "reachable",
    hops: [
      { index: 1, component: "No VPC attachment", type: "ENI", action: "ROUTE", detail: "Lambda runs outside VPC, uses public AWS network directly" },
      { index: 2, component: "S3 public endpoint", type: "ENI", action: "ALLOW", detail: "TLS connection established — no VPC endpoint used (data traverses public internet)" },
    ],
    ran_at: ago(1),
    duration_ms: 89,
    blocking_reason: "Note: Lambda not in VPC — S3 traffic traverses public internet. Consider VPC + S3 Gateway Endpoint.",
  },
  {
    id: "ct-004",
    source: "10.0.1.45 (staging)",
    source_type: "EC2",
    destination: "10.0.3.200 (prod-db)",
    destination_type: "EC2",
    port: 3306,
    protocol: "TCP",
    result: "timeout",
    hops: [
      { index: 1, component: "sg-staging-app", type: "SecurityGroup", action: "ALLOW", detail: "Outbound 0.0.0.0/0" },
      { index: 2, component: "rtb-staging", type: "RouteTable", action: "ROUTE", detail: "10.0.0.0/16 → local — routes exist" },
      { index: 3, component: "acl-prod-nacl", type: "NACL", action: "DENY", detail: "NACL rule 90 denies INBOUND from 10.0.1.0/24 to prod subnet" },
    ],
    ran_at: ago(0.5),
    duration_ms: 30_004,
    blocking_component: "acl-prod-nacl",
    blocking_reason: "NACL rule 90 explicitly denies cross-environment traffic from staging subnet to prod — correct isolation, verify intentional",
  },
];

// ─── Route entries ─────────────────────────────────────────────────────────────

export const MOCK_ROUTES: RouteEntry[] = [
  { destination: "10.0.0.0/16", target: "local", target_type: "local", state: "active", vpc_id: "vpc-0123abcd", route_table_id: "rtb-0prodmain", subnet_ids: ["subnet-a", "subnet-b", "subnet-c"] },
  { destination: "0.0.0.0/0", target: "igw-0prod1234", target_type: "igw", state: "active", vpc_id: "vpc-0123abcd", route_table_id: "rtb-0prodmain", subnet_ids: ["subnet-a"] },
  { destination: "0.0.0.0/0", target: "nat-0abcd5678", target_type: "nat", state: "active", vpc_id: "vpc-0123abcd", route_table_id: "rtb-0prodpriv", subnet_ids: ["subnet-b", "subnet-c"] },
  { destination: "172.16.0.0/12", target: "blackhole", target_type: "blackhole", state: "blackhole", vpc_id: "vpc-0123abcd", route_table_id: "rtb-0prodmain", subnet_ids: ["subnet-a"] },
  { destination: "10.200.0.0/16", target: "pcx-0peering", target_type: "pcx", state: "active", vpc_id: "vpc-0123abcd", route_table_id: "rtb-0prodpriv", subnet_ids: ["subnet-b"] },
  { destination: "0.0.0.0/0", target: "tgw-0transit", target_type: "tgw", state: "active", vpc_id: "vpc-0789ijkl", route_table_id: "rtb-0dev", subnet_ids: ["subnet-dev-a"] },
];

// ─── DNS resolutions ──────────────────────────────────────────────────────────

export const MOCK_DNS: DNSResolution[] = [
  { id: "dns-001", hostname: "api-prod.internal.acme.com", resolved_ips: ["10.0.2.45", "10.0.3.67"], resolver: "Route53_Resolver", latency_ms: 4, status: "resolved", ran_at: ago(0.05) },
  { id: "dns-002", hostname: "legacy-service.acme.com", resolved_ips: [], resolver: "Route53_Resolver", latency_ms: 2000, status: "nxdomain", ran_at: ago(0.1) },
  { id: "dns-003", hostname: "database.prod.internal", resolved_ips: ["10.0.4.200"], resolver: "VPC_DNS", latency_ms: 1, status: "resolved", ran_at: ago(0.03) },
  { id: "dns-004", hostname: "updates.example.com", resolved_ips: [], resolver: "External", latency_ms: 5000, status: "timeout", ran_at: ago(0.5) },
];

// ─── Scenarios ─────────────────────────────────────────────────────────────────

export const INFRA_SCENARIOS: Scenario[] = [
  {
    id: "missing_logs",
    name: "Missing VPC Flow Logs",
    description: "Simulate a VPC with flow logging disabled. Network traffic is invisible — no audit trail for suspicious lateral movement.",
    severity: "HIGH",
    affected_resources: ["vpc-0789ijkl (dev-vpc)"],
    simulation_steps: [
      "Flow log config is absent on vpc-0789ijkl",
      "Anomalous port scan from 10.0.5.200 → 10.0.4.0/24 goes undetected",
      "GuardDuty cannot correlate network behavior without flow data",
      "Incident response has no packet-level evidence for forensics",
    ],
    expected_findings: ["HIGH: VPC flow logs disabled — no network visibility", "MEDIUM: GuardDuty NetworkFinding confidence reduced"],
    remediation_preview: ["Enable VPC Flow Logs to S3 with 90-day retention", "Enable GuardDuty to correlate flow data automatically"],
  },
  {
    id: "misconfigured_sg",
    name: "Misconfigured SG + NACL Conflict",
    description: "SG allows DB access, but NACL rule 100 overrides and blocks all TCP — creating a false sense of security in SG config.",
    severity: "CRITICAL",
    affected_resources: ["sg-0def5678 (prod-db-sg)", "acl-0abc1234 (prod-nacl)"],
    simulation_steps: [
      "DB SG rule allows app-tier SG inbound on 5432",
      "NACL rule 90 (higher priority) denies all TCP from 10.0.1.0/24",
      "Connectivity test: app → db returns TIMEOUT",
      "Team adds 0.0.0.0/0 to NACL to fix (overcorrects)",
      "DB now accessible from entire internet",
    ],
    expected_findings: ["CRITICAL: NACL rule bypasses SG isolation, team added overly-permissive fix", "HIGH: DB accessible from internet"],
    remediation_preview: ["Add specific NACL rule for app subnet before rule 90", "Remove the 0.0.0.0/0 NACL rule added as emergency fix"],
  },
  {
    id: "public_edge_exposure",
    name: "WAF-less Public API Exposure",
    description: "Production API with no WAF and no auth — immediate SQLi/path traversal risk.",
    severity: "CRITICAL",
    affected_resources: ["agr-0a1b2c/prod (acme-data-api)", "E1A2B3C4D5E6F7 (CloudFront)"],
    simulation_steps: [
      "CloudFront distribution has no WAF ACL",
      "API Gateway stage 'prod' uses auth_type NONE",
      "SQLi payload sent to /data?id=1 OR 1=1",
      "Request passes WAF (none), CloudFront, API GW to origin",
      "Database query returns all records",
    ],
    expected_findings: ["CRITICAL: No WAF protection on edge", "CRITICAL: API Gateway no auth", "HIGH: Data exposure risk"],
    remediation_preview: ["Attach WAF ACL with SQLi ruleset to CloudFront", "Add API GW authorizer or resource policy", "Enable CloudFront access logs immediately"],
  },
  {
    id: "failed_isolation",
    name: "Failed EC2 Isolation Attempt",
    description: "Incident responder attaches quarantine SG to compromised instance, but existing SG is still attached — isolation is incomplete.",
    severity: "HIGH",
    affected_resources: ["i-0a1b2c3d4e5f6789 (prod-web-01)"],
    simulation_steps: [
      "Responder creates quarantine-sg with no inbound/outbound rules",
      "AWS EC2 allows multiple SGs — most permissive rule wins",
      "prod-web-sg still attached — instance remains reachable",
      "Responder thinks isolation is complete but it is not",
      "Lateral movement continues for 4+ hours",
    ],
    expected_findings: ["HIGH: Isolation incomplete — multiple SGs attached", "MEDIUM: Containment gap in IR playbook"],
    remediation_preview: ["Detach ALL existing SGs before attaching quarantine-sg", "Use AWS Systems Manager to automate isolation without SG overlap", "Update IR playbook with correct isolation procedure"],
  },
  {
    id: "delayed_telemetry",
    name: "Delayed CloudWatch Telemetry",
    description: "CloudWatch Logs agent lag causes 15-minute gaps in security event data — alerts fire late or not at all.",
    severity: "MEDIUM",
    affected_resources: ["prod-worker-02 (i-0b2c3d4e5f678901)", "CloudWatch Log Group: /aws/vpc/staging-flow-logs"],
    simulation_steps: [
      "CloudWatch Logs agent on prod-worker-02 loses connectivity at 02:14 UTC",
      "Buffer fills — agent drops events after 5 minutes",
      "Security Hub metric filter triggers 18 minutes after the anomalous API call",
      "Alert fires 22 minutes after the event — SLA for CRITICAL is 4 hours but investigation is delayed",
    ],
    expected_findings: ["MEDIUM: Log agent telemetry lag > 5 minutes on prod-worker-02", "LOW: CloudWatch buffer overflow risk — agent not in persistent flush mode"],
    remediation_preview: ["Configure CWAgent with force_flush_interval: 5", "Set up CloudWatch agent health metric alert", "Evaluate Kinesis Data Firehose for high-throughput log shipping"],
  },
];
