// Data Protection — deterministic mock data
import type {
  TLSEndpoint, CertificateEntry, PlaintextChannel,
  StorageEncryptionEntry, PublicSnapshot,
  RetentionPolicy, S3LifecycleRule,
  SecretEntry, KMSKeyEntry,
  AuditTrailEvent, DPScenario,
} from "./types";

function ago(days: number) { return new Date(Date.now() - days * 86_400_000).toISOString(); }
function fromNow(days: number) { return new Date(Date.now() + days * 86_400_000).toISOString(); }
function hash(s: string) { let h = 0; for (let i = 0; i < s.length; i++) { h = (Math.imul(31, h) + s.charCodeAt(i)) | 0; } return Math.abs(h).toString(16).padStart(8, "0"); }

// ─── TLS Endpoints ─────────────────────────────────────────────────────────────

export const MOCK_TLS_ENDPOINTS: TLSEndpoint[] = [
  {
    id: "tls-001", name: "prod-alb", resource_type: "ALB",
    resource_id: "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/prod-alb/0ab1cd",
    min_tls_version: "1.2", max_tls_version: "1.3",
    pfs_enabled: true, hsts_enabled: true, http_redirect_to_https: true,
    compliance: "compliant", region: "us-east-1", certificate_id: "cert-001",
  },
  {
    id: "tls-002", name: "legacy-api-alb", resource_type: "ALB",
    resource_id: "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/legacy-alb/9f8e7d",
    min_tls_version: "1.0", max_tls_version: "1.2",
    pfs_enabled: false, hsts_enabled: false, http_redirect_to_https: false,
    compliance: "non_compliant", region: "us-east-1", certificate_id: "cert-002",
  },
  {
    id: "tls-003", name: "cloudsec.acme.io (CloudFront)", resource_type: "CloudFront",
    resource_id: "E1A2B3C4D5E6F7",
    min_tls_version: "1.2", max_tls_version: "1.3",
    pfs_enabled: true, hsts_enabled: false, http_redirect_to_https: true,
    compliance: "partial", region: "us-east-1", certificate_id: "cert-003",
  },
  {
    id: "tls-004", name: "prod-rds-mysql", resource_type: "RDS",
    resource_id: "arn:aws:rds:us-east-1:123456789012:db:prod-mysql-01",
    min_tls_version: "1.2", max_tls_version: "1.3",
    pfs_enabled: false, hsts_enabled: false, http_redirect_to_https: false,
    compliance: "compliant", region: "us-east-1", certificate_id: null,
  },
  {
    id: "tls-005", name: "acme-data-api (API GW)", resource_type: "API_GW",
    resource_id: "agr-0a1b2c/prod",
    min_tls_version: "1.2", max_tls_version: "1.3",
    pfs_enabled: true, hsts_enabled: true, http_redirect_to_https: true,
    compliance: "compliant", region: "us-east-1", certificate_id: null,
  },
  {
    id: "tls-006", name: "staging-elb", resource_type: "ALB",
    resource_id: "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/staging-alb/1c2d3e",
    min_tls_version: "1.1", max_tls_version: "1.2",
    pfs_enabled: true, hsts_enabled: false, http_redirect_to_https: false,
    compliance: "partial", region: "us-east-1", certificate_id: "cert-004",
  },
];

// ─── Certificates ─────────────────────────────────────────────────────────────

export const MOCK_CERTIFICATES: CertificateEntry[] = [
  {
    id: "cert-001",
    domain: "*.acme.io",
    san_domains: ["acme.io", "api.acme.io", "cloudsec.acme.io"],
    issuer: "Amazon", issued_at: ago(180), expires_at: fromNow(185),
    days_remaining: 185,
    auto_renew: true, acm_managed: true,
    compliance: "compliant",
    attached_to: ["prod-alb", "E1A2B3C4D5E6F7"],
    algorithm: "RSA-2048",
  },
  {
    id: "cert-002",
    domain: "legacy-api.acme.com",
    san_domains: [],
    issuer: "DigiCert", issued_at: ago(340), expires_at: fromNow(25),
    days_remaining: 25,
    auto_renew: false, acm_managed: false,
    compliance: "non_compliant",
    attached_to: ["legacy-api-alb"],
    algorithm: "RSA-2048",
  },
  {
    id: "cert-003",
    domain: "cloudsec.acme.io",
    san_domains: ["www.cloudsec.acme.io"],
    issuer: "Amazon", issued_at: ago(90), expires_at: fromNow(275),
    days_remaining: 275,
    auto_renew: true, acm_managed: true,
    compliance: "compliant",
    attached_to: ["E1A2B3C4D5E6F7"],
    algorithm: "ECDSA-P256",
  },
  {
    id: "cert-004",
    domain: "staging.acme.io",
    san_domains: ["api.staging.acme.io"],
    issuer: "Let's Encrypt", issued_at: ago(85), expires_at: fromNow(-5),
    days_remaining: -5,
    auto_renew: true, acm_managed: false,
    compliance: "non_compliant",
    attached_to: ["staging-elb"],
    algorithm: "ECDSA-P256",
  },
  {
    id: "cert-005",
    domain: "internal.acme.corp",
    san_domains: ["*.internal.acme.corp"],
    issuer: "Internal CA", issued_at: ago(30), expires_at: fromNow(335),
    days_remaining: 335,
    auto_renew: false, acm_managed: false,
    compliance: "compliant",
    attached_to: ["bastion-host", "internal-vpn"],
    algorithm: "RSA-4096",
  },
];

// ─── Plaintext channels ────────────────────────────────────────────────────────

export const MOCK_PLAINTEXT: PlaintextChannel[] = [
  {
    id: "pt-001", resource_id: "sg-0abc1234", resource_name: "prod-web-sg",
    resource_type: "EC2 SG Rule", protocol: "HTTP", port: 80,
    description: "ALB listener on port 80 accepting unencrypted traffic. No redirect to HTTPS configured.",
    severity: "HIGH", detected_at: ago(3),
  },
  {
    id: "pt-002", resource_id: "redis-001", resource_name: "prod-elasticache-redis",
    resource_type: "ElastiCache", protocol: "Redis", port: 6379,
    description: "Redis cluster does not require in-transit encryption. Credentials and session data transmitted in plaintext.",
    severity: "CRITICAL", detected_at: ago(14),
  },
  {
    id: "pt-003", resource_id: "mq-001", resource_name: "dev-rabbit-mq",
    resource_type: "Amazon MQ", protocol: "AMQP", port: 5672,
    description: "Dev MQ broker allows unencrypted AMQP connections on port 5672 (non-SSL).",
    severity: "MEDIUM", detected_at: ago(7),
  },
];

// ─── Storage encryption ────────────────────────────────────────────────────────

export const MOCK_STORAGE_ENCRYPTION: StorageEncryptionEntry[] = [
  {
    id: "enc-001", resource_id: "company-prod-data", resource_name: "company-prod-data",
    resource_type: "S3", encrypted: true, algorithm: "aws:kms",
    kms_key_id: "arn:aws:kms:us-east-1:123456789012:key/mrk-abc123",
    kms_key_alias: "alias/prod-s3-key",
    compliance: "compliant", public_accessible: false,
    region: "us-east-1", data_classification: "CRITICAL",
  },
  {
    id: "enc-002", resource_id: "acme-staging-logs", resource_name: "acme-staging-logs",
    resource_type: "S3", encrypted: true, algorithm: "SSE-S3",
    kms_key_id: null, kms_key_alias: null,
    compliance: "partial", public_accessible: false,
    region: "us-east-1", data_classification: "INTERNAL",
  },
  {
    id: "enc-003", resource_id: "dev-scratch-bucket", resource_name: "dev-scratch-bucket",
    resource_type: "S3", encrypted: false, algorithm: "NONE",
    kms_key_id: null, kms_key_alias: null,
    compliance: "non_compliant", public_accessible: true,
    region: "us-east-1", data_classification: "INTERNAL",
  },
  {
    id: "enc-004", resource_id: "vol-0a1b2c3d", resource_name: "prod-web-01 /dev/sda1",
    resource_type: "EBS", encrypted: true, algorithm: "aws:kms",
    kms_key_id: "arn:aws:kms:us-east-1:123456789012:key/mrk-ebs456",
    kms_key_alias: "alias/ebs-default",
    compliance: "compliant", public_accessible: false,
    region: "us-east-1", data_classification: "SENSITIVE",
  },
  {
    id: "enc-005", resource_id: "vol-0d4e5f6g", resource_name: "prod-worker-02 /dev/sda1",
    resource_type: "EBS", encrypted: false, algorithm: "NONE",
    kms_key_id: null, kms_key_alias: null,
    compliance: "non_compliant", public_accessible: false,
    region: "us-east-1", data_classification: "SENSITIVE",
  },
  {
    id: "enc-006", resource_id: "prod-mysql-01", resource_name: "prod-mysql-01",
    resource_type: "RDS", encrypted: true, algorithm: "aws:kms",
    kms_key_id: "arn:aws:kms:us-east-1:123456789012:key/mrk-rds789",
    kms_key_alias: "alias/rds-prod-key",
    compliance: "compliant", public_accessible: false,
    region: "us-east-1", data_classification: "CRITICAL",
  },
  {
    id: "enc-007", resource_id: "dev-dynamo-test", resource_name: "dev-dynamo-test",
    resource_type: "DynamoDB", encrypted: true, algorithm: "aws:kms",
    kms_key_id: null, kms_key_alias: null,
    compliance: "partial", public_accessible: false,
    region: "us-east-1", data_classification: "INTERNAL",
  },
];

// ─── Public snapshots ──────────────────────────────────────────────────────────

export const MOCK_PUBLIC_SNAPSHOTS: PublicSnapshot[] = [
  {
    id: "snap-001", snapshot_id: "snap-0abc1234def56789",
    resource_type: "EBS", source_resource: "vol-0a1b2c3d (prod-web-01)",
    created_at: ago(4), size_gb: 100,
    encrypted: false,
    severity: "CRITICAL",
    description: "Unencrypted EBS snapshot of production web server marked as public. Data accessible to any AWS account.",
    region: "us-east-1",
  },
  {
    id: "snap-002", snapshot_id: "rds:prod-mysql-01-2026-01-15",
    resource_type: "RDS", source_resource: "prod-mysql-01",
    created_at: ago(71), size_gb: 450,
    encrypted: true,
    severity: "HIGH",
    description: "RDS automated snapshot shared with another AWS account (987654321098). May be legacy sharing from migration.",
    region: "us-east-1",
  },
];

// ─── Retention policies ────────────────────────────────────────────────────────

export const MOCK_RETENTION: RetentionPolicy[] = [
  {
    id: "ret-001", resource_id: "company-prod-data", resource_name: "company-prod-data (S3)",
    resource_type: "S3_Bucket", required_days: 2555, actual_days: 2555,
    framework: "HIPAA", compliance: "compliant", last_reviewed: ago(14),
    drift_days: 0, data_classification: "CRITICAL",
  },
  {
    id: "ret-002", resource_id: "/aws/vpc/prod-flow-logs", resource_name: "prod-flow-logs (CWL)",
    resource_type: "CloudWatch_Logs", required_days: 90, actual_days: 14,
    framework: "SOC2", compliance: "non_compliant", last_reviewed: ago(180),
    drift_days: -76, data_classification: "SENSITIVE",
  },
  {
    id: "ret-003", resource_id: "acme-cloudtrail", resource_name: "acme-cloudtrail",
    resource_type: "CloudTrail", required_days: 365, actual_days: 365,
    framework: "PCI-DSS", compliance: "compliant", last_reviewed: ago(7),
    drift_days: 0, data_classification: "SENSITIVE",
  },
  {
    id: "ret-004", resource_id: "/app/prod/audit-logs", resource_name: "prod audit logs (CWL)",
    resource_type: "CloudWatch_Logs", required_days: 365, actual_days: 30,
    framework: "SOC2", compliance: "non_compliant", last_reviewed: ago(90),
    drift_days: -335, data_classification: "CRITICAL",
  },
  {
    id: "ret-005", resource_id: "prod-mysql-01-backup", resource_name: "prod-mysql-01 backups",
    resource_type: "RDS_Backup", required_days: 35, actual_days: 7,
    framework: "PCI-DSS", compliance: "non_compliant", last_reviewed: ago(60),
    drift_days: -28, data_classification: "CRITICAL",
  },
  {
    id: "ret-006", resource_id: "acme-staging-logs", resource_name: "acme-staging-logs (S3)",
    resource_type: "S3_Bucket", required_days: 30, actual_days: 90,
    framework: "Internal", compliance: "partial", last_reviewed: ago(45),
    drift_days: 60, data_classification: "INTERNAL",
  },
];

// ─── S3 lifecycle rules ────────────────────────────────────────────────────────

export const MOCK_S3_LIFECYCLE: S3LifecycleRule[] = [
  {
    id: "lc-001", bucket: "company-prod-data", rule_id: "archive-after-90",
    enabled: true, prefix: "logs/",
    transitions: [{ storage_class: "STANDARD_IA", days: 30 }, { storage_class: "GLACIER", days: 90 }],
    expiration_days: 2555, noncurrent_expiration_days: 30, abort_incomplete_multipart_days: 7,
    compliance: "compliant",
  },
  {
    id: "lc-002", bucket: "acme-staging-logs", rule_id: "default",
    enabled: false, prefix: "",
    transitions: [],
    expiration_days: null, noncurrent_expiration_days: null, abort_incomplete_multipart_days: null,
    compliance: "non_compliant",
  },
  {
    id: "lc-003", bucket: "dev-scratch-bucket", rule_id: "cleanup-30d",
    enabled: true, prefix: "",
    transitions: [],
    expiration_days: 30, noncurrent_expiration_days: 7, abort_incomplete_multipart_days: 3,
    compliance: "compliant",
  },
  {
    id: "lc-004", bucket: "acme-flow-logs", rule_id: "glacier-archive",
    enabled: true, prefix: "prod/",
    transitions: [{ storage_class: "STANDARD_IA", days: 60 }, { storage_class: "DEEP_ARCHIVE", days: 365 }],
    expiration_days: null, noncurrent_expiration_days: 90, abort_incomplete_multipart_days: 7,
    compliance: "partial",
  },
];

// ─── Secrets ───────────────────────────────────────────────────────────────────

export const MOCK_SECRETS: SecretEntry[] = [
  {
    id: "sec-001",
    secret_name: "prod/db/mysql-master-password",
    secret_arn: "arn:aws:secretsmanager:us-east-1:123456789012:secret:prod/db/mysql-master-password-aBcDeF",
    description: "Production MySQL master password",
    secret_type: "Database",
    rotation_enabled: true, rotation_days: 30,
    last_rotated: ago(12), next_rotation: fromNow(18),
    days_since_rotation: 12,
    rotation_status: "active",
    compliance: "compliant",
    kms_key_id: "arn:aws:kms:us-east-1:123456789012:key/mrk-abc123",
    used_by: ["prod-web-01", "prod-api-01", "acme-data-processor"],
    last_accessed: ago(0.1),
  },
  {
    id: "sec-002",
    secret_name: "prod/stripe/api-key",
    secret_arn: "arn:aws:secretsmanager:us-east-1:123456789012:secret:prod/stripe/api-key-gHiJkL",
    description: "Stripe live API secret key",
    secret_type: "API_Key",
    rotation_enabled: false, rotation_days: null,
    last_rotated: ago(387), next_rotation: null,
    days_since_rotation: 387,
    rotation_status: "stale",
    compliance: "non_compliant",
    kms_key_id: null,
    used_by: ["acme-payment-service"],
    last_accessed: ago(0.5),
  },
  {
    id: "sec-003",
    secret_name: "prod/github/deploy-token",
    secret_arn: "arn:aws:secretsmanager:us-east-1:123456789012:secret:prod/github/deploy-token-mNoPqR",
    description: "GitHub deployment token for CI/CD",
    secret_type: "OAuth",
    rotation_enabled: false, rotation_days: null,
    last_rotated: null, next_rotation: null,
    days_since_rotation: 9999,
    rotation_status: "never_rotated",
    compliance: "non_compliant",
    kms_key_id: null,
    used_by: ["github-actions-runner", "codebuild-prod"],
    last_accessed: ago(0.2),
  },
  {
    id: "sec-004",
    secret_name: "staging/redis/auth-token",
    secret_arn: "arn:aws:secretsmanager:us-east-1:123456789012:secret:staging/redis/auth-token-sTuVwX",
    description: "ElastiCache Redis auth token for staging",
    secret_type: "Generic",
    rotation_enabled: true, rotation_days: 90,
    last_rotated: ago(45), next_rotation: fromNow(45),
    days_since_rotation: 45,
    rotation_status: "active",
    compliance: "compliant",
    kms_key_id: "arn:aws:kms:us-east-1:123456789012:key/mrk-abc123",
    used_by: ["staging-app"],
    last_accessed: ago(1),
  },
  {
    id: "sec-005",
    secret_name: "prod/twilio/account-sid",
    secret_arn: "arn:aws:secretsmanager:us-east-1:123456789012:secret:prod/twilio/account-sid-yZaBcD",
    description: "Twilio Account SID and Auth Token",
    secret_type: "API_Key",
    rotation_enabled: false, rotation_days: null,
    last_rotated: ago(195), next_rotation: null,
    days_since_rotation: 195,
    rotation_status: "stale",
    compliance: "non_compliant",
    kms_key_id: null,
    used_by: ["acme-notification-service"],
    last_accessed: ago(0.3),
  },
];

// ─── KMS Keys ──────────────────────────────────────────────────────────────────

export const MOCK_KMS_KEYS: KMSKeyEntry[] = [
  {
    id: "kms-001",
    key_id: "mrk-abc123",
    key_alias: "alias/prod-s3-key",
    description: "Prod S3 and Secrets Manager encryption key",
    key_usage: "ENCRYPT_DECRYPT",
    key_spec: "SYMMETRIC_DEFAULT",
    rotation_enabled: true,
    last_rotation: ago(180),
    state: "Enabled",
    policy_issues: [],
    usage_7d: [1240, 980, 1450, 1320, 870, 1100, 930],
    deletion_date: null,
    compliance: "compliant",
    key_manager: "CUSTOMER",
  },
  {
    id: "kms-002",
    key_id: "mrk-ebs456",
    key_alias: "alias/ebs-default",
    description: "Default EBS volume encryption key",
    key_usage: "ENCRYPT_DECRYPT",
    key_spec: "SYMMETRIC_DEFAULT",
    rotation_enabled: false,
    last_rotation: null,
    state: "Enabled",
    policy_issues: ["Key policy allows kms:* to all principals (*) — over-permissive", "No key grant restrictions on Decrypt action"],
    usage_7d: [450, 390, 410, 480, 395, 420, 405],
    deletion_date: null,
    compliance: "non_compliant",
    key_manager: "CUSTOMER",
  },
  {
    id: "kms-003",
    key_id: "mrk-rds789",
    key_alias: "alias/rds-prod-key",
    description: "RDS production encryption key",
    key_usage: "ENCRYPT_DECRYPT",
    key_spec: "SYMMETRIC_DEFAULT",
    rotation_enabled: true,
    last_rotation: ago(95),
    state: "Enabled",
    policy_issues: [],
    usage_7d: [88, 72, 95, 81, 67, 90, 75],
    deletion_date: null,
    compliance: "compliant",
    key_manager: "CUSTOMER",
  },
  {
    id: "kms-004",
    key_id: "mrk-old123",
    key_alias: "alias/legacy-app-key",
    description: "Legacy application key scheduled for deletion",
    key_usage: "ENCRYPT_DECRYPT",
    key_spec: "SYMMETRIC_DEFAULT",
    rotation_enabled: false,
    last_rotation: ago(400),
    state: "PendingDeletion",
    policy_issues: ["Key scheduled for deletion in 12 days"],
    usage_7d: [0, 0, 2, 0, 0, 0, 1],
    deletion_date: fromNow(12),
    compliance: "partial",
    key_manager: "CUSTOMER",
  },
  {
    id: "kms-005",
    key_id: "alias/aws/s3",
    key_alias: "alias/aws/s3",
    description: "AWS managed key for S3",
    key_usage: "ENCRYPT_DECRYPT",
    key_spec: "SYMMETRIC_DEFAULT",
    rotation_enabled: true,
    last_rotation: ago(365),
    state: "Enabled",
    policy_issues: [],
    usage_7d: [3400, 3100, 3780, 2900, 3200, 3500, 3050],
    deletion_date: null,
    compliance: "compliant",
    key_manager: "AWS",
  },
];

// ─── Audit trail ──────────────────────────────────────────────────────────────

export const MOCK_AUDIT_TRAIL: AuditTrailEvent[] = [
  {
    id: "aud-001",
    timestamp: ago(0.05),
    actor: "System",
    actor_type: "system",
    resource_id: "prod/db/mysql-master-password",
    action: "RotateSecret",
    detail: "Automatic rotation triggered by schedule. Lambda rotator executed successfully.",
    outcome: "success",
    evidence_hash: hash("aud-001-rotate"),
  },
  {
    id: "aud-002",
    timestamp: ago(3),
    actor: "alice.chen",
    actor_type: "engineer",
    resource_id: "mrk-ebs456",
    action: "PutKeyPolicy",
    detail: "Key policy updated to restrict Decrypt to specific IAM roles (prior: allow all principals).",
    outcome: "warning",
    evidence_hash: hash("aud-002-keypolicy"),
  },
  {
    id: "aud-003",
    timestamp: ago(4),
    actor: "Config Rule",
    actor_type: "automation",
    resource_id: "dev-scratch-bucket",
    action: "DetectNonCompliance",
    detail: "S3 bucket found without SSE encryption. Rule: s3-bucket-server-side-encryption-enabled",
    outcome: "failure",
    evidence_hash: hash("aud-003-s3-enc"),
  },
  {
    id: "aud-004",
    timestamp: ago(5),
    actor: "bob.martinez",
    actor_type: "engineer",
    resource_id: "cert-004",
    action: "CertificateRenewalAttempt",
    detail: "Manual renewal attempt for staging.acme.io. Let's Encrypt ACME challenge failed — DNS record not updated.",
    outcome: "failure",
    evidence_hash: hash("aud-004-cert"),
  },
  {
    id: "aud-005",
    timestamp: ago(7),
    actor: "Security Hub",
    actor_type: "system",
    resource_id: "snap-0abc1234def56789",
    action: "DetectPublicSnapshot",
    detail: "EBS snapshot detected as publicly accessible. Finding: EC2.21 — Public EBS snapshot.",
    outcome: "failure",
    evidence_hash: hash("aud-005-snapshot"),
  },
  {
    id: "aud-006",
    timestamp: ago(14),
    actor: "System",
    actor_type: "system",
    resource_id: "prod/stripe/api-key",
    action: "RotationOverdue",
    detail: "Secret rotation overdue by 357 days. Rotation policy requires 30-day cycle. Auto-rotation not configured.",
    outcome: "warning",
    evidence_hash: hash("aud-006-stripe"),
  },
];

// ─── Scenarios ─────────────────────────────────────────────────────────────────

export const DP_SCENARIOS: DPScenario[] = [
  {
    id: "expired_certificate",
    name: "Expired TLS Certificate",
    description: "staging.acme.io certificate expired 5 days ago. Browsers show NET::ERR_CERT_DATE_INVALID. Traffic is impacted.",
    severity: "CRITICAL",
    affected_resources: ["cert-004 (staging.acme.io)", "staging-elb"],
    simulation_steps: [
      "cert-004 expires at 23:59 UTC — Let's Encrypt auto-renewal failed",
      "staging-elb continues serving traffic with the expired cert",
      "Modern browsers block requests with HSTS enforcement",
      "Health checks from monitoring begin failing — alert fires",
      "On-call engineer investigates — cert expiry confirmed",
    ],
    expected_findings: ["CRITICAL: Certificate expired — staging.acme.io", "HIGH: TLS endpoint serving expired certificate for 5+ days", "MEDIUM: Let's Encrypt ACME renewal failure not alerted"],
    remediation_preview: ["Request new certificate via ACM or Let's Encrypt", "Validate DNS challenge record is in place", "Update ALB listener with new certificate ARN", "Enable ACM auto-renewal for future prevention"],
  },
  {
    id: "plaintext_transport",
    name: "Plaintext HTTP in Production",
    description: "ALB port 80 listener accepts unencrypted HTTP. Production PII data traverses the network in plaintext.",
    severity: "HIGH",
    affected_resources: ["legacy-api-alb", "prod-web-sg (port 80 inbound)"],
    simulation_steps: [
      "prod user submits a form with email + credit card number",
      "Browser sends HTTP POST to legacy-api-alb:80",
      "Traffic is unencrypted between client and ALB",
      "VPC flow logs show traffic on port 80 — no encryption flag",
      "PCI-DSS requirement 4.2.1 violated — cardholder data unencrypted in transit",
    ],
    expected_findings: ["HIGH: Plaintext HTTP listener active on prod ALB", "CRITICAL (PCI): CHD transmitted without TLS", "MEDIUM: TLS 1.0 also accepted on same endpoint"],
    remediation_preview: ["Create HTTPS:443 listener with compliant certificate", "Add HTTP:80 redirect rule to listener", "Delete HTTP:80 listener after HTTPS confirmed working", "Enable HSTS header via ALB response headers policy"],
  },
  {
    id: "unencrypted_storage",
    name: "Unencrypted EBS Volume",
    description: "prod-worker-02 has an unencrypted EBS volume containing application data and OS secrets.",
    severity: "HIGH",
    affected_resources: ["vol-0d4e5f6g (prod-worker-02 /dev/sda1)"],
    simulation_steps: [
      "EBS volume vol-0d4e5f6g created without encryption before org-level default was set",
      "Instance profile allows EC2:CreateSnapshot — any authorized principal can snapshot",
      "Snapshot of unencrypted volume copies data without protection",
      "Auditor runs AWS Config rule encrypted-volumes — violation detected",
    ],
    expected_findings: ["HIGH: Unencrypted EBS volume in production", "MEDIUM: Instance allows snapshot creation without CMK requirement"],
    remediation_preview: ["Stop instance, create snapshot, copy snapshot with encryption enabled (CMK)", "Create new encrypted volume from encrypted snapshot", "Detach unencrypted volume and attach encrypted replacement", "Enable EBS encryption by default at account level"],
  },
  {
    id: "public_snapshot",
    name: "Public EBS Snapshot Exposure",
    description: "Production web server EBS snapshot is publicly accessible. Any AWS account can copy data.",
    severity: "CRITICAL",
    affected_resources: ["snap-0abc1234def56789 (100GB, unencrypted)"],
    simulation_steps: [
      "Developer runs aws ec2 modify-snapshot-attribute --create-volume-permission --user-groups all",
      "Snapshot becomes globally restorable — any AWS account can copy it",
      "Snapshot contains /etc/shadow, SSH keys, app config with DB credentials",
      "Security Hub finding EC2.21 fires — 3 hours later",
      "Threat actor calls aws ec2 copy-snapshot from external account — data exfiltrated",
    ],
    expected_findings: ["CRITICAL: Public EBS snapshot — unencrypted production data exposed", "CRITICAL: Potential credential exposure in snapshot contents", "HIGH: No SCG/SCP preventing public snapshot sharing"],
    remediation_preview: ["Immediately: aws ec2 modify-snapshot-attribute --remove CreateVolumePermission for all", "Rotate all credentials that may be in the snapshot", "Create SCP denying ec2:ModifySnapshotAttribute with AllUsers", "Enable Security Hub EC2.21 alerting with < 15min SLA"],
  },
  {
    id: "retention_drift",
    name: "Log Retention Policy Drift",
    description: "CloudWatch log groups set to 14-day retention vs SOC2 requirement of 90 days.",
    severity: "HIGH",
    affected_resources: ["/aws/vpc/prod-flow-logs", "/app/prod/audit-logs (30 days vs 365 required)"],
    simulation_steps: [
      "Log group /aws/vpc/prod-flow-logs created with default 14-day retention",
      "SOC2 control CC7.2 requires 90 days minimum for security logs",
      "Security incident occurred 45 days ago — logs needed for forensics are deleted",
      "SOC2 auditor requests evidence — log groups show insufficient retention",
      "Audit finding raised — SOC2 type II qualification at risk",
    ],
    expected_findings: ["HIGH: VPC flow logs retention 76 days below SOC2 requirement", "CRITICAL: Audit log group retention 335 days below SOC2 requirement"],
    remediation_preview: ["Update log group retention policy to 90+ days immediately", "Enable S3 export for long-term archival if CWL retention limits cost", "Implement AWS Config rule cloud-trail-log-file-validation-enabled", "Add retention check to infrastructure CI/CD pipeline"],
  },
  {
    id: "stale_rotation",
    name: "Stale Secret — 387 Days No Rotation",
    description: "Stripe live API key has not been rotated in 387 days. Rotation was disabled after a production incident workaround.",
    severity: "HIGH",
    affected_resources: ["prod/stripe/api-key (Secrets Manager)"],
    simulation_steps: [
      "prod/stripe/api-key rotation disabled on 2025-03-01 — 'emergency workaround'",
      "Key not rotated for 387 days — well beyond PCI-DSS 90-day requirement",
      "Stripe key leaked via GitHub Actions log exposure (unmasked env var)",
      "Attacker uses key to query Stripe API — customer payment data accessible",
      "Stripe detects unusual geo for API calls — key revoked, but attacker already has data",
    ],
    expected_findings: ["HIGH: Secret not rotated in 387 days — PCI-DSS violation", "HIGH: Stripe API key has no Secrets Manager rotation configured", "MEDIUM: Secret used by service without key usage monitoring"],
    remediation_preview: ["Immediately rotate the Stripe API key in Stripe dashboard", "Update prod/stripe/api-key with new value in Secrets Manager", "Enable Secrets Manager rotation with custom Lambda for Stripe", "Add secret rotation policy check to compliance scanner"],
  },
  {
    id: "overpermissive_key",
    name: "Over-Permissive KMS Key Policy",
    description: "KMS key alias/ebs-default allows kms:* to all principals — any IAM entity can decrypt EBS-encrypted data.",
    severity: "HIGH",
    affected_resources: ["mrk-ebs456 (alias/ebs-default)"],
    simulation_steps: [
      "KMS key created with default policy — allows kms:* to account root",
      "Policy never restricted — any IAM role with kms:Decrypt can decrypt any EBS volume",
      "Dev engineer with excessive IAM permissions calls kms:Decrypt on prod EBS snapshot",
      "Sensitive data from production snapshot decrypted without intended authorization",
      "No CloudTrail alert configured for cross-role KMS decrypt — goes undetected",
    ],
    expected_findings: ["HIGH: KMS key policy allows kms:Decrypt to all IAM principals", "MEDIUM: No key grant restrictions on Decrypt action", "MEDIUM: No CloudTrail alert on kms:Decrypt for this key"],
    remediation_preview: ["Restrict key policy to specific IAM roles (prod-app-role, prod-rds-role)", "Remove wildcard kms:* and replace with explicit allowed actions", "Add CloudTrail + CloudWatch alarm on Decrypt for this key", "Rotate key material to invalidate any previously computed grants"],
  },
];
